volumes:
  redis_volume:
  postgres_data:
  pgadmin-data:


services:
  redis:
    image: redis:7.0.1-alpine
    container_name: incident_tracker_redis
    restart: always
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - redis_volume:/data
    networks:
      - incident_tracker

  db:
    image: postgres:15.2-alpine
    container_name: incident_tracker_db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - incident_tracker

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "${PGADMIN_EXTERNAL_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - incident_tracker

  api:
    container_name: incident_tracker_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    develop:
      watch:
        - action: sync+restart
          path: src/incident_tracker
          target: /app/incident_tracker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/monitoring/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - ./src/incident_tracker/database/sqlalchemy/migrations:/app/incident_tracker/database/sqlalchemy/migrations
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - incident_tracker

  nginx:
    image: nginx:1.29.0-alpine-slim
    container_name: incident_tracker_nginx
    restart: always
    volumes:
      - ./gateway/nginx/default-local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - incident_tracker


networks:
  incident_tracker:
    external: true
